#!/system/bin/sh
# By: Hashcode
# Last Edit: 10/30/2012
/system/etc/safestrap/bbx mount -o remount,rw rootfs
/system/etc/safestrap/bbx cp /system/etc/safestrap/bbx /sbin/bbx
/system/etc/safestrap/bbx chmod 755 /sbin/bbx
/system/etc/safestrap/bbx chown 0.2000 /sbin/bbx
/sbin/bbx sh /system/bin/setup_fs-hijack &

